# Generated by Django 5.0.6 on 2024-06-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legsettings",
            name="on_sl",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ReExecuteLeg", "ReExecuteLeg"),
                    ("ReEnterLeg", "ReEnterLeg"),
                    ("KeepLegRunning", "KeepLegRunning"),
                    (
                        "partial_reexecute_opposite_leg",
                        "partial_reexecute_opposite_leg",
                    ),
                    ("partial_sqoff_legs", "partial_sqoff_legs"),
                    ("partial_execute_legs", "partial_execute_legs"),
                ],
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="legsettings",
            name="on_tp",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ReExecuteLeg", "ReExecuteLeg"),
                    ("ReEnterLeg", "ReEnterLeg"),
                    ("KeepLegRunning", "KeepLegRunning"),
                    ("partial_execute_legs", "partial_execute_legs"),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
